cactus_path: download
# Paths made relative to the Snakemake --directory (results/minigraph_cactus)
input_file: cactus_input.txt
output_dir: output
final_prefix: khv
maf_reference: KHV_U_trunc
tmp_dir: tmp
use_gpu: False

rule_resources:
  default:
    partition: standard
    mem_mb: 8000
    cpus: 4
    time: 120
  preprocess:
    partition: standard
    mem_mb: 8000
    cpus: 4
    time: 120
  blast:
    partition: standard
    mem_mb: 16000
    cpus: 8
    gpus: 0
    time: 240
  align:
    partition: standard
    mem_mb: 16000
    cpus: 8
    time: 240
  convert:
    partition: standard
    mem_mb: 4000
    cpus: 2
    time: 60
  copy_hal:
    partition: standard
    mem_mb: 2000
    cpus: 1
    time: 30
  append:
    partition: standard
    mem_mb: 4000
    cpus: 2
    time: 60
  maf:
    partition: standard
    mem_mb: 8000
    cpus: 4
    time: 180
